name: Link Check

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # - name: markdownlint-cli
      #   uses: nosborn/github-action-markdown-cli@v3.0.1
      #   with:
      #     files: ./docs/
      #     config_file: .markdownlint.json
      - name: markdownlint-cli
        uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: "**/*.md"